#!/usr/bin/env node
/**
 * Write the service worker after a build, with the hashed asset names baked in.
 *
 * Vite fingerprints its output, so the precache list can only be known once the
 * build exists. Generating the worker here — rather than shipping a static one
 * that guesses — means a new deploy replaces the old cache exactly, with no
 * stale chunk left behind to 404 at runtime.
 */
import { readdirSync, statSync, writeFileSync, readFileSync } from 'node:fs'
import { join, resolve, relative, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createHash } from 'node:crypto'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const dist = resolve(root, 'web/dist')
const base = process.env.COUNTBOOK_BASE ?? '/'

const walk = (dir) =>
  readdirSync(dir).flatMap((name) => {
    const p = join(dir, name)
    return statSync(p).isDirectory() ? walk(p) : [p]
  })

const files = walk(dist)
  .map((p) => relative(dist, p).split('\\').join('/'))
  .filter((p) => p !== 'sw.js' && !p.endsWith('.map'))

// The version is the content of the build, so an unchanged build does not evict
// a warm cache and any change evicts all of it.
const version = createHash('sha256')
  .update(files.map((f) => f + statSync(join(dist, f)).size).join('|'))
  .digest('hex')
  .slice(0, 12)

const precache = ['./', ...files].map((f) => JSON.stringify(base + f.replace(/^\.\//, '')))

const sw = `// GENERATED by scripts/gen-sw.mjs — do not edit.
const VERSION = ${JSON.stringify(version)}
const CACHE = 'countbook-' + VERSION
const PRECACHE = [${precache.join(', ')}]

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const { request } = event
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  // Sync traffic must never be served from a cache: a stale ledger is worse
  // than no ledger, and these responses are not ours to keep.
  if (url.origin !== self.location.origin) return

  // A navigation is answered from the network when there is one, so a deploy is
  // picked up on the next launch, and from the cached shell when there is not.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((res) => {
          const copy = res.clone()
          void caches.open(CACHE).then((c) => c.put(${JSON.stringify(base)}, copy))
          return res
        })
        .catch(() => caches.match(${JSON.stringify(base)}).then((r) => r ?? caches.match(request))),
    )
    return
  }

  // Everything else is fingerprinted and immutable, so the cache is authoritative.
  event.respondWith(
    caches.match(request).then(
      (hit) =>
        hit ??
        fetch(request).then((res) => {
          if (res.ok && res.type === 'basic') {
            const copy = res.clone()
            void caches.open(CACHE).then((c) => c.put(request, copy))
          }
          return res
        }),
    ),
  )
})
`

writeFileSync(join(dist, 'sw.js'), sw)

// A project page has no server-side rewrite, so a deep link 404s unless the
// 404 document is the app itself.
writeFileSync(join(dist, '404.html'), readFileSync(join(dist, 'index.html')))

console.log(`sw.js  version ${version}  ${files.length} precached files`)
